[debug] [2023-10-06T02:23:26.227Z] ----------------------------------------------------------------------
[debug] [2023-10-06T02:23:26.231Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-10-06T02:23:26.232Z] CLI Version:   12.5.4
[debug] [2023-10-06T02:23:26.233Z] Platform:      win32
[debug] [2023-10-06T02:23:26.233Z] Node Version:  v18.4.0
[debug] [2023-10-06T02:23:26.235Z] Time:          Thu Oct 05 2023 19:23:26 GMT-0700 (Pacific Daylight Time)
[debug] [2023-10-06T02:23:26.235Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-10-06T02:23:26.446Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-10-06T02:23:26.447Z] > authorizing via signed-in user (divyareddy0205@gmail.com)
[debug] [2023-10-06T02:23:26.448Z] [iam] checking project netflix-gpt-689a1 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-10-06T02:23:26.451Z] > refreshing access token with scopes: []
[debug] [2023-10-06T02:23:26.455Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-06T02:23:26.456Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-06T02:23:47.665Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------659304036195596362951387","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4007:817::200a:443
[debug] [2023-10-06T02:23:47.668Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-06T02:23:47.671Z] > refreshing access token with scopes: []
[debug] [2023-10-06T02:23:47.673Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-10-06T02:23:47.673Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-10-06T02:24:08.734Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------773163495999395642941801","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4007:817::200a:443
[debug] [2023-10-06T02:24:08.735Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-10-06T02:24:13.770Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\Admin\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:254:49)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[error] 
[error] Error: An unexpected error has occurred.
